services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  postgres:
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    image: postgres
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - backend
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
volumes:
  db:
    driver: local
networks:
  backend:
    driver: bridge